### ISSUE TITLE
Separate layout pass in order to make it possible to determine which tiles are visible ahead of time

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/egui_tiles#34]
This is needed for cases where data needs to prepared for every visible tile before getting the `pane_ui` callback (potentially in parallel).

**Comment by emilk** [comment]
I don't think we need a layout pass for this. You can find all visible tiles by recursively visiting all tiles, but only the active tab of a tab container.

**Comment by emilk** [comment]
I added a helper function for getting the "active" (visible) tiles in https://github.com/rerun-io/egui_tiles/pull/42
