### ISSUE TITLE
Duplicate Id when creating 2 pane trees in the same app.

### ISSUE THREAD

**Issue by GuillaumeSchmid** [rerun-io/egui_tiles#64]
I have 2 separate pane trees in 2 different areas of my user interface.
They have different behaviors and I don't want to mix the panes between the 2 trees.
I noticed that both trees when rendering creates same Ids for pane separator:
![image](https://github.com/rerun-io/egui_tiles/assets/18464073/d8dd6c12-7010-402c-b825-cd8fc3593b87)
Is this a bug or is there a way to avoid this?

**Comment by emilk** [comment]
Are you using a globally unique Id for each tree? https://docs.rs/egui_tiles/latest/egui_tiles/struct.Tree.html#method.new

**Comment by GuillaumeSchmid** [comment]
I think so, I use the following code to create the trees
let players_tree = Tree::new(Id::new("Group_pane_").with(group_id), root_id, tiles);
let state_tree = Tree::new(Id::new("states_pane_").with(group_id), grid_id, tiles);

The 2 different strings shoudl produce different id.
