### ISSUE TITLE
Tree height and width are f32 but deserialised as Option<f32>

### ISSUE THREAD

**Issue by lwiklendt** [rerun-io/egui_tiles#86]
`Tree::height` and `Tree::width` are `f32` but are trying to be deserialised as `Option<f32>` resulting in an error

https://github.com/rerun-io/egui_tiles/blob/3e7f32435543660f6c763747bb73462d5d4aa579/src/tree.rs#L57-L62

**Comment by kgv** [comment]
relevant: https://github.com/emilk/egui/issues/5176

**Comment by emilk** [comment]
I think we need to revert
* https://github.com/rerun-io/egui_tiles/pull/85

**Comment by s-nie** [comment]
Either revert it or also handle the serialization the same way:

`serde(serialize_with = "serialize_f32_infinity_as_null")` for the fields and then:

```rust
#[cfg(feature = "serde")]
fn serialize_f32_infinity_as_null<S: serde::Serializer>(
    t: &f32,
    serializer: S,
) -> Result<S::Ok, S::Error> {
    if t.is_infinite() {
        serializer.serialize_none()
    } else {
        serializer.serialize_f32(*t)
    }
}
```

**Comment by lwiklendt** [comment]
> handle the serialization the same way

The deserialiser is expecting an `Option<f32>`, so you would need to serialise it as an `Option<f32>`. That is, you would need to use something like `serializer.serialize_option(t)` instead of `serializer.serialize_f32(*t)`. However, this would result in a surprising incoherence between the struct fields as `f32` and their serialisation as `Option<f32>`.

**Comment by emilk** [comment]
Can JSON just add support for +/-inf already 🙄

**Comment by lwiklendt** [comment]
Wow, TIL JSON doesn't have inf and NaN support.
I'm using RON in my projects, so I was blissfully ignorant of the JSON problem.
